image: node:10.15.0

pages:
  cache:
    paths:
    - node_modules/
  stage: deploy
  script:
  - npm install
  - npm run build
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
