backend:
  name: git-gateway
  branch: netlifycms

media_folder: "static/images"
public_folder: "/images"

site_url: https://netlifycms.speirs.dev

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-content" }
          - { label: "title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/content/pages/projects.md"
        label: "Projects"
        name: "projects"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "projects-content" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/content/pages/tags.md"
        label: "Tags"
        name: "tags"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "tags-content" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/content/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-content" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "src/content/projects"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", format: 'YYYY-MM-DD', widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Hidden", name: "hidden", widget: "boolean", default: false }
      - { label: "Github", name: "github", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
